name: template-sync

on:
  push:
    branches:
      - master
      - chore/test-sync

jobs:
  template_sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # important!
      - uses: ahmadnassri/action-template-repository-sync@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: false 
