name: template-sync

on:
  # manual trigger
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v0.3.1-draft
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: vtex-sites/gatsby.store
          upstream_branch: main # defaults to main
          pr_labels: template-sync # defaults to chore,template-sync
